version: '2'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    hostname: kafka
    expose:
      - "9092"
      - "2181"
    environment:
      TOPICS: gt_imp_report,gt_clk_report,gt_event_report
  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: always
  mongodb:
    container_name: mongo
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/docker/db:/data/db
    ports:
      - 27017:27017
    expose:
      - "27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
